### ISSUE TITLE
Problems with BCL installation on macs

### ISSUE THREAD

**Issue by yongwang123222** [BCLCommons/bcl#13]
User 
**This is the error I get when installing, pointing out that：**
 _BZ2_bzCompressEnd, referenced from:
      bcl::bzip2::StreamBuffer::Close() in bcl_bzip2_stream_buffer.cpp.o
  _BZ2_bzCompressInit, referenced from:
      bcl::bzip2::StreamBuffer::Initialize() in bcl_bzip2_stream_buffer.cpp.o
      bcl::bzip2::StreamBuffer::InitOutput() in bcl_bzip2_stream_buffer.cpp.o
  _BZ2_bzDecompress, referenced from:
      bcl::bzip2::StreamBuffer::underflow() in bcl_bzip2_stream_buffer.cpp.o
  _BZ2_bzDecompressEnd, referenced from:
      bcl::bzip2::StreamBuffer::Close() in bcl_bzip2_stream_buffer.cpp.o
  _BZ2_bzDecompressInit, referenced from:
      bcl::bzip2::StreamBuffer::InitInput() in bcl_bzip2_stream_buffer.cpp.o
  _gzclose, referenced from:
      bcl::gzip::StreamBuffer::~StreamBuffer() in bcl_gzip_stream_buffer.cpp.o
      bcl::gzip::StreamBuffer::Close() in bcl_gzip_stream_buffer.cpp.o
  _gzopen, referenced from:
      bcl::gzip::StreamBuffer::Open(char const*, unsigned int) in bcl_gzip_stream_buffer.cpp.o
  _gzread, referenced from:
      bcl::gzip::StreamBuffer::underflow() in bcl_gzip_stream_buffer.cpp.o
  _gzseek, referenced from:
      bcl::gzip::StreamBuffer::seekoff(long long, std::__1::ios_base::seekdir, unsigned int) in bcl_gzip_stream_buffer.cpp.o
  _gzwrite, referenced from:
      bcl::gzip::StreamBuffer::~StreamBuffer() in bcl_gzip_stream_buffer.cpp.o
      bcl::gzip::StreamBuffer::overflow(int) in bcl_gzip_stream_buffer.cpp.o
      bcl::gzip::StreamBuffer::Flush() in bcl_gzip_stream_buffer.cpp.o
      bcl::gzip::StreamBuffer::sync() in bcl_gzip_stream_buffer.cpp.o
clang: error: linker command failed with exit code 1 (use -v to see invocation)
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[3]: *** [bin/bcl-example-apps-static.exe] Error 1
make[3]: *** [bin/bcl-apps-static.exe] Error 1
make[3]: Target `example/CMakeFiles/bcl-example-apps-static.dir/build' not remade because of errors.
make[3]: Target `apps/CMakeFiles/bcl-apps-static.dir/build' not remade because of errors.
make[2]: *** [example/CMakeFiles/bcl-example-apps-static.dir/all] Error 2
make[2]: *** [apps/CMakeFiles/bcl-apps-static.dir/all] Error 2
ld: Undefined symbols:
  _BZ2_bzCompress, referenced from:
      bcl::bzip2::StreamBuffer::Close() in bcl_bzip2_stream_buffer.cpp.o
      bcl::bzip2::StreamBuffer::Close() in bcl_bzip2_stream_buffer.cpp.o
      bcl::bzip2::StreamBuffer::CompressCurrentBlock() in bcl_bzip2_stream_buffer.cpp.o
      bcl::bzip2::StreamBuffer::FinalizeOutputStream() in bcl_bzip2_stream_buffer.cpp.o
      bcl::bzip2::StreamBuffer::Flush() in bcl_bzip2_stream_buffer.cpp.o
      bcl::bzip2::StreamBuffer::overflow(int) in bcl_bzip2_stream_buffer.cpp.o
      bcl::bzip2::StreamBuffer::sync() in bcl_bzip2_stream_buffer.cpp.o
      bcl::bzip2::StreamBuffer::sync() in bcl_bzip2_stream_buffer.cpp.o
      ...
  _BZ2_bzCompressEnd, referenced from:
      bcl::bzip2::StreamBuffer::Close() in bcl_bzip2_stream_buffer.cpp.o
  _BZ2_bzCompressInit, referenced from:
      bcl::bzip2::StreamBuffer::Initialize() in bcl_bzip2_stream_buffer.cpp.o
      bcl::bzip2::StreamBuffer::InitOutput() in bcl_bzip2_stream_buffer.cpp.o
  _BZ2_bzDecompress, referenced from:
      bcl::bzip2::StreamBuffer::underflow() in bcl_bzip2_stream_buffer.cpp.o
  _BZ2_bzDecompressEnd, referenced from:
      bcl::bzip2::StreamBuffer::Close() in bcl_bzip2_stream_buffer.cpp.o
  _BZ2_bzDecompressInit, referenced from:
      bcl::bzip2::StreamBuffer::InitInput() in bcl_bzip2_stream_buffer.cpp.o
  _gzclose, referenced from:
      bcl::gzip::StreamBuffer::~StreamBuffer() in bcl_gzip_stream_buffer.cpp.o
      bcl::gzip::StreamBuffer::Close() in bcl_gzip_stream_buffer.cpp.o
  _gzopen, referenced from:
      bcl::gzip::StreamBuffer::Open(char const*, unsigned int) in bcl_gzip_stream_buffer.cpp.o
  _gzread, referenced from:
      bcl::gzip::StreamBuffer::underflow() in bcl_gzip_stream_buffer.cpp.o
  _gzseek, referenced from:
      bcl::gzip::StreamBuffer::seekoff(long long, std::__1::ios_base::seekdir, unsigned int) in bcl_gzip_stream_buffer.cpp.o
  _gzwrite, referenced from:
      bcl::gzip::StreamBuffer::~StreamBuffer() in bcl_gzip_stream_buffer.cpp.o
      bcl::gzip::StreamBuffer::overflow(int) in bcl_gzip_stream_buffer.cpp.o
      bcl::gzip::StreamBuffer::Flush() in bcl_gzip_stream_buffer.cpp.o
      bcl::gzip::StreamBuffer::sync() in bcl_gzip_stream_buffer.cpp.o
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[3]: *** [bin/bcl-example-static.exe] Error 1
make[3]: Target `example/CMakeFiles/bcl-example-static.dir/build' not remade because of errors.
make[2]: *** [example/CMakeFiles/bcl-example-static.dir/all] Error 2
make[2]: Target `CMakeFiles/static.dir/all' not remade because of errors.
make[1]: *** [CMakeFiles/static.dir/rule] Error 2
make[1]: Target `static' not remade because of errors.
make: *** [static] Error 2
21.850u 26.450s 0:12.61 383.0%	0+0k 0+0io 37322pf+0w

Because of my lack of knowledge in computer programming, I've installed it a few times and keep getting this problem, I've successfully installed bcl on ubuntu but still keep getting this installation problem on mac, is there any solution to this? Thanks, your help is much needed!

**Comment by roccomoretti** [comment]
I don't have much experience with Macs, but from the messages it looks like the issue is the bzip2 and zlib dependencies. I don't believe the BCL ships with those libraries, so you'll have to install the development version(*) of them separately, using your standard operating system techniques. (I don't know what that is like on Mac.)

*) the development version is different from the "normal" user version -- you'll need the version with the header files included

**Comment by yongwang123222** [comment]
thanks for your help. yes ,the problems is related with bzip2 and zlib dependencies.
