### ISSUE TITLE
the error of running bcl-4.3.1.dmg.tar.gz of apple in system macOS sonoma14.0

### ISSUE THREAD

**Issue by yongwang123222** [BCLCommons/bcl#14]
(base) wangyong@wangyongdeMacBook-Pro inputs % bcl molecule:ConformerGenerator -add_h -neutralize -ensemble_filenames osimertinib.clean.sdf.gz -conformers_single_file ../outputs/osimertinib.symrmsd_cluster.confs.sdf.gz -max_iterations 2000 -top_models 25 -conformation_comparer SymmetryRMSD 0.25
bcl molecule:ConformerGenerator -add_h -neutralize -ensemble_filenames osimertinib.clean.sdf.gz -conformers_single_file ../outputs/osimertinib.symrmsd_cluster.confs.sdf.gz -max_iterations 2000 -top_models 25 -conformation_comparer SymmetryRMSD 0.25 
BCL v4.3.1, compiled on Wed Dec 21 16:58:36 2022
=std=bcl=> executing application: molecule:ConformerGenerator
=crt=bcl::random=> Seed was set to 5489!
=crt=bcl::random=> Seed was set to 5489!

 Status: [                    ] 0% 0/1 molecules read
=crt=bcl::app=>  iterating through ensemble in ANC - 0
BCL Error: -1 | function: MustOpenIFStream | file: bcl_io_file.h | line: 253
===> Could not open cod.substructure.txt.gz for reading
BCL Error: -1 | function: MustOpenIFStream | file: bcl_io_file.h | line: 253
===> Could not open cod.substructure.txt.gz for reading
BCL Error: -1 | function: ~Mutex | file: bcl_sched_mutex.cpp | line: 91
===> cannot delete a mutex that is still locked
BCL Error: -1 | function: ~Mutex | file: bcl_sched_mutex.cpp | line: 91
===> cannot delete a mutex that is still locked
=std=bcl::util=> FindFrags has run for 0.000243 seconds
=std=bcl::util=> RotamerLibraryFile reading files has run for 0.000686 secondsbug**

My computer system version is macos sonoma14.0, I downloaded the mac version of BioChemicalLibrary-4.3.1 (bcl-4.3.1.dmg.tar.gz) that you posted, unzipped it, and then ran the tutorial1 example in blc-workshop2022 (described above). But at the end, the following error appears, I don't know how to correct this error, I request your help, thank you!

**Comment by brownbp1** [comment]
Hi @yongwang123222. I see that you are getting "Could not open cod.substructure.txt.gz". The mutex stuff is secondary to the initial failure.

Can you confirm that you have bcl/rotamer_library/cod.substructure.txt.gz? Can you also run "ldd /bcl/build/apple64_release/bin/bcl-apps-static.exe" or whatever your executable is named and show me the output? Can you tell me how you setup your environment? Did you alias the BCL executable or export the bin to PATH? Or neither? Also, does the command work if you change into the bcl/ directory and try running again using the relative path back to the tutorial files?

Did you try this on Linux? If so, what was the result?

Thanks,
Ben

**Comment by yongwang123222** [comment]
**First of all, thank you very much for your reply, at first, because I didn't compile it successfully on my mac, I downloaded bcl-4.3.1.dmg.tar.gz directly (bcl-4.3.1 for apple). Then I refer to bcl_workshop_2022/bcl_workshop_2022/Tutorial_1 to learn about bcl, and when I run the bcl molecule:Filter application, everything works fine, and I get the correct output as well. Here is the directory of my rotamer_library,and output of molecule:Filter** 
![rotamer library](https://github.com/BCLCommons/bcl/assets/146175248/de699707-44ea-466d-9b2d-ac72b1440a5c)
![molecule_Filter_application](https://github.com/BCLCommons/bcl/assets/146175248/a4d1068c-c8c7-48dc-b593-0c2170c77e3b)
![molecule_Filer_output](https://github.com/BCLCommons/bcl/assets/146175248/0f8a816e-e135-42a5-9bb7-36e11614e910)

This is the environment variable #BCL set in my ~/.zshrc
export BCL=/Users/wangyong/Applications/BioChemicalLibrary-4.3.1
export PATH=/Users/wangyong/Applications/BioChemicalLibrary-4.3.1:${PATH}, 
because I downloaded the version that Apple doesn't need to compile, and I use it directly after unzipping it, so there is no PATH of  BioChemicalLibrary-4.3.1. Bin folder.

**I've run other programs where molecule:Coordinates doesn't work either, it seems that whenever cod.substructure.txt.gz in rotamer_library is involved, the program reports this error status:**
 [ ] 0% 0/1 molecules readBCL Error: -1 | function: MustOpenIFStream | file: bcl_io_file.h | line: 253
===> Unable to open cod.substructure.txt.gz for reading
BCL Error: -1 | function: MustOpenIFStream | file: bcl_io_file.h | line: 253
===> Cannot open cod.substructure.txt.gz for reading.
BCL Error: -1 | function: ~Mutex | file: bcl_sched_mutex.cpp | line: 91
===> Unable to delete a mutex that is still locked.
BCL Error: -1 | function: ~Mutex | file: bcl_sched_mutex.cpp | line: 91
===> Unable to remove a mutex that is still locked.

Similarly I also encountered the same error after compiling bcl in ubuntu 20.04, and certain applications involving cod.substructure.txt.gz reported an error. I've looked up a lot of content but I don't understand what's going on, and because I'm not good at computer languages myself, that's why I'm asking for help, I'm very much looking forward to your reply again, thanks! @brownbp1

**Comment by yongwang123222** [comment]
**This is the environment variable set by ~/.bashrc in my Ubuntu 20.04** 
![bashrc](https://github.com/BCLCommons/bcl/assets/146175248/a82facdc-c384-4310-a0dd-ae61573dda02)

**This is what I get when I run the moleculer:ConformerGenerator application**
(base) yongwang@DESKTOP-L4LFLPS:/mnt/d/bcl/bcl_workshop_2022/BCL_Workshop_2022/Tutorial_1/inputs$ bcl-apps-static.exe molecule:ConformerGenerator -ensemble_filenames osimertinib.clean.sdf.gz -conformers_single_file ../outputs_wy/osimertinib.quick_confs.sdf.gz -max_iterations 500 -top_models 50
bcl-apps-static.exe molecule:ConformerGenerator -ensemble_filenames osimertinib.clean.sdf.gz -conformers_single_file ../outputs_wy/osimertinib.quick_confs.sdf.gz -max_iterations 500 -top_models 50
BCL v4.3.1, r0, compiled on Thu Oct 26 16:46:03 2023
=std=bcl=> executing application: molecule:ConformerGenerator
=crt=bcl::random=> Seed was set to 5489!
=crt=bcl::random=> Seed was set to 5489!

============================================================================================================================================================================================

BCL FLAGS

-message_level not set
   <level> Standard (default)
   <verbosity> Summary (default)
-logger not set
   <> Default (default)
   <identifier>  (default)
-help not set
-readme not set
-file_compressed_alternatives not set
-file_compression not set
   <compression_type> Uncompressed (default)
-enums_files not set
-random_seed not set
   <seed> 5489 (default)
-model_path not set
   <model_path_name>  (default)
-histogram_path not set
   <path>  (default)
-opencl not set
   <platform> Disable (default)
-scheduler not set
   <scheduler> Serial (default)
   <number_cpus> 1 (default)

============================================================================================================================================================================================

APPLICATION FLAGS

-help not set
-readme not set
-ensemble_filenames set
   <filenames> osimertinib.clean.sdf.gz
-ensemble_start not set
   <start> 0 (default)
-ensemble_max not set
   <number> 18446744073709551615 (default)
-add_h not set
-remove_h not set
-neutralize not set
   <method> BondOrderAndpH (default)
-explicit_aromaticity not set
-natives not set
-conformation_comparer not set
   <rmsd_type> SymmetryRMSD (default)
   <tolerance> 0.0 (default)
-max_iterations set
   <max_iterations> 500
-output_ligand_data not set
-top_models set
   <top_models> 50
-failed_3D not set
-output_rmsd_score not set
-conformers_single_file set
   <conformers_single_file> ../outputs_wy/osimertinib.quick_confs.sdf.gz
-conformers_separate_files not set
-minimum_number_conformations not set
-change_chirality not set
-generate_3D not set
-cluster not set
-skip_cluster not set
-rnd_dihedral_mutate_weight not set
   <mutate_weight> 0.0 (default)
-skip_rotamer_dihedral_sampling not set
-skip_bond_angle_sampling not set
-skip_ring_sampling not set
-clash_resolution not set
   <max_clash_resolution_iterations> 0.1 (default)
-max_clash_tolerance not set
   <max_clash_tolerance> 0.1 (default)
-rotamer_library not set
   <> cod (default)

============================================================================================================================================================================================

 Status: [                    ] 0% 0/1 molecules read
=crt=bcl::app=>  iterating through ensemble in ANC - 0
BCL Error: -1 | function: MustOpenIFStream | file: bcl_io_file.h | line: 253
===> Could not open cod.substructure.txt.gz for reading
Call Stack
bcl-apps-static.exe: void bcl::io::File::MustOpenIFStream<bcl::io::IFStream>(bcl::io::IFStream&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::_Ios_Openmode)
bcl-apps-static.exe: bcl::chemistry::RotamerLibraryFile::RetrieveRotamerSubstructureTree() const
bcl-apps-static.exe: bcl::chemistry::SearchFragmentLibraryFromTree::LoadRotamerLibraryInformation() const
bcl-apps-static.exe: bcl::chemistry::SearchFragmentLibraryFromTree::FindFragmentsOfMolecule(bcl::chemistry::ConformationInterface const&) const
bcl-apps-static.exe: bcl::chemistry::SampleConformations::operator()(bcl::chemistry::FragmentComplete const&) const
bcl-apps-static.exe: bcl::app::ConformerGenerator::ConformationSampling(bcl::chemistry::FragmentComplete const&, unsigned long const&) const
bcl-apps-static.exe: bcl::app::ConformerGenerator::Main() const
bcl-apps-static.exe: main
/lib/x86_64-linux-gnu/libc.so.6: __libc_start_main
bcl-apps-static.exe: _start
**BCL Error: -1 | function: MustOpenIFStream | file: bcl_io_file.h | line: 253
===> Could not open cod.substructure.txt.gz for reading
BCL Error: -1 | function: ~Mutex | file: bcl_sched_mutex.cpp | line: 91
===> cannot delete a mutex that is still locked**
Call Stack
bcl-apps-static.exe: bcl::sched::Mutex::~Mutex()
/lib/x86_64-linux-gnu/libc.so.6: on_exit
bcl-apps-static.exe: bcl::util::Assert::Exit(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int, char const*, int, char const*, bool const&)
bcl-apps-static.exe: void bcl::io::File::MustOpenIFStream<bcl::io::IFStream>(bcl::io::IFStream&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::_Ios_Openmode)
bcl-apps-static.exe: bcl::chemistry::RotamerLibraryFile::RetrieveRotamerSubstructureTree() const
bcl-apps-static.exe: bcl::chemistry::SearchFragmentLibraryFromTree::LoadRotamerLibraryInformation() const
bcl-apps-static.exe: bcl::chemistry::SearchFragmentLibraryFromTree::FindFragmentsOfMolecule(bcl::chemistry::ConformationInterface const&) const
bcl-apps-static.exe: bcl::chemistry::SampleConformations::operator()(bcl::chemistry::FragmentComplete const&) const
bcl-apps-static.exe: bcl::app::ConformerGenerator::ConformationSampling(bcl::chemistry::FragmentComplete const&, unsigned long const&) const
bcl-apps-static.exe: bcl::app::ConformerGenerator::Main() const
bcl-apps-static.exe: main
/lib/x86_64-linux-gnu/libc.so.6: __libc_start_main
bcl-apps-static.exe: _start
**BCL Error: -1 | function: ~Mutex | file: bcl_sched_mutex.cpp | line: 91**
===> cannot delete a mutex that is still locked
=std=bcl::util=> FindFrags has run for 0.294088 seconds
=std=bcl::util=> RotamerLibraryFile reading files has run for 0.298403 seconds


**this is Contents of the rotamer_libarary folder**
![rotamer_directory](https://github.com/BCLCommons/bcl/assets/146175248/766950e9-8897-444c-9baf-0d69cfef72d1)
![the content of romater_libarary](https://github.com/BCLCommons/bcl/assets/146175248/8e2aa32f-1f58-4d0d-bf3c-06af25e67302)

**I don't know what my problem is, and I'm asking for your help!**

**Comment by brownbp1** [comment]
Does the command work if you change into the bcl/ directory and try running again using the relative path back to the tutorial files?

Please also provide the output to 'which bcl' if 'bcl' is your executable. Similarly, please provide 'ldd bcl' using the full path to 'bcl'.

**Comment by yongwang123222** [comment]
Thank you very, very much for your advice, I will input the file into a relative path, I get the correct output, it seems to be a command path problem, simply too happy, thank you very much for solving the problem that has been bothering me for a week!

**Comment by brownbp1** [comment]
In this case, I recommend you set an alias for the full path to your bcl executable. In your shell, you can do something like
`readlink -e build/apple64_release/bin/bcl-apps-static.exe`
from your bcl/ directory to get the full path, and then you can give it an alias via
`alias bcl="/full/path/to/bcl/executable"` where /full/path/to/bcl/executable is the output from the above readlink command.
Then you will be able to run from any directory. The issue is just that the path to the executable is used to help find other data, such as the rotamer library, and in this case it was just not able to find the full path.

Glad this helped.

**Comment by yongwang123222** [comment]
Thanks for your help!  !  Good luck for you,Prof. ---- Replied Message ----FromBenjamin P. ***@***.***>Date10/31/2023 22:13 ***@***.***> ***@***.***>***@***.***>SubjectRe: [BCLCommons/bcl] the error of running bcl-4.3.1.dmg.tar.gz of apple in system macOS sonoma14.0 (Issue #14)
In this case, I recommend you set an alias for the full path to your bcl executable. In your shell, you can do something like
readlink -e bcl/build/apple64_release/bin/bcl-apps-static.exe
to get the full path, and then you can give it an alias via
alias bcl="/full/path/to/bcl/executable" where /full/path/to/bcl/executable is the output from the above readlink command.
Glad this helped.

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/BCLCommons/bcl/issues/14#issuecomment-1787194403",
"url": "https://github.com/BCLCommons/bcl/issues/14#issuecomment-1787194403",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
