### ISSUE TITLE
Problem in converting 2D-sdf files into 3D-sdf files for molecules

### ISSUE THREAD

**Issue by carosl** [BCLCommons/bcl#18]
Hello,

I am trying to use BCL for the first time. My main goal is to use it to convert 2D sdf files of molecules into 3D files. The command I am using is:

bcl.exe molecule:ConformerGenerator -ensemble_filenames input2D.sdf -add_h -generate_3D -minimum_number_conformations 1 -skip_cluster

My input file has 22 (2D-sdf) molecules. I would expect to have 22 (3D-sdf) molecules after using this command. But I only get 6 molecules converted. Why?

Also, I don't get why I get the "conformationComparison" section, since I put the flag "-skip_cluster" in my command. What can I do to just convert my 2D molecules in 3D?

I am leaving a picture of the message I get after running the command and an example of one of the molecules I am using.

Thank you in advance.

Laura

![image](https://github.com/BCLCommons/bcl/assets/152205269/b2dd9c2f-5d98-4af7-923b-27a66ef14bfe)

Example of a 2D molecule:
![image](https://github.com/BCLCommons/bcl/assets/152205269/fc9709ef-b57d-42ad-8f78-76bff6867dd7)
![image](https://github.com/BCLCommons/bcl/assets/152205269/6539b784-ff45-4180-b549-b9492e2a66f8)

**Comment by brownbp1** [comment]
Hi. We recommend different settings in the paper (PMID 33351632). Try the following command instead:
`bcl.exe molecule:ConformerGenerator -add_h -ensemble_filenames  input2D.sdf -top_models 1 -max_iterations 2000 -conformation_comparer SymmetryRMSD 0.25 -cluster`

At the end of the day, the BCL conformer generator utilizes a stochastic dihedral fragment sampler to build 3D conformers. It is not a rule-based method. If there are no fragments in the fragment database, it may be required to generate an initial conformer using an alternative method, such as Corina or OpenBabel. There are advantages and disadavantages to each approach depending on your needs.
