### ISSUE TITLE
Can't compile BCL on RedHat with pump

### ISSUE THREAD

**Issue by kimdn** [BCLCommons/bcl#8]
**Describe the bug**
![Screen Shot 2022-10-03 at 1 14 49 PM](https://user-images.githubusercontent.com/3903446/193671238-6423bed6-049e-46d8-983c-9b375144ee80.png)

**To Reproduce**
I had to add
```
set BCL_DIRECTORY = "/people/kimd999/ncAA_rcfs/DN/rosetta/bcl/git_repo/bcl"
set TOOLCHAIN_ALIAS = linux64
set BUILD_TYPE_ALIAS = release
set TOOLCHAIN = x86_64-unknown-linux-gnu

```

to ./scripts/build/check_pump_make.csh

to avoid

this kind of message
`BCL_DIRECTORY: Undefined variable.`

**Desktop (please complete the following information):**
 - Redhat OS 6.6

**Comment by brownbp1** [comment]
Instead of running "check_pump_cmake.sh" you should run "build_cmdline.linux.sh", which sets the variables you describe.

Script contents:

> #!/bin/bash
> 
> TOOLCHAIN_ALIAS=linux64 
> TOOLCHAIN=x86_64-unknown-linux-gnu 
> BUILD_TYPE_ALIAS=release
> BCL_DIRECTORY=`pwd`
> export TOOLCHAIN_ALIAS TOOLCHAIN BUILD_TYPE_ALIAS BCL_DIRECTORY
> mkdir -p build/${TOOLCHAIN_ALIAS}_${BUILD_TYPE_ALIAS}
> 
> python2 ./cmake/scripts/CheckCmakeLists.py ./ -o  
> 
> python2 ./scripts/code/CreateNamespaceForwardHeaders.py ./ -o
> 
> if [ -z "${SHARED+x}" ] ; then
>   tcsh ./scripts/build/check_pump_make.csh -k static 
> else
>   tcsh ./scripts/build/check_pump_make.csh -k shared
> fi

**Comment by kimdn** [comment]
I see.

Since I can't open extracted eclipse on my redhat,

![1](https://user-images.githubusercontent.com/3903446/193682650-ad37b144-8347-4255-a8e2-7b84ff10e1c6.jpg)


I just wanted to try
https://github.com/BCLCommons/bcl/blob/master/COMPILING.md#development-environment---non-eclipse
So I ran step 1~6 accordingly.
